/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sendilkumarn;

public class App {
    public static void main(String[] args) {
        System.out.println("Run the tests to verify the Reference Counting Algorithm");
    }
}
